apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eureka-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: CD/DEV
    repoURL: https://github.com/shahravir/eureka.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

